version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    ports: [ "2181:2181" ]
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    depends_on: [ zookeeper ]
    ports: [ "9092:9092" ]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.3
    depends_on: [ kafka ]
    ports: [ "8081:8081" ]
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092

  kafka-connect:
    build:
      context: ./kafka-connect
      dockerfile: Dockerfile
    image: custom-kafka-connect:7.5.3
    depends_on: [ kafka ]
    ports: [ "8083:8083" ]
    environment:
      # обязательные CONNECT_*
      CONNECT_BOOTSTRAP_SERVERS: kafka:29092
      CONNECT_GROUP_ID: "1"

      # внутренние топики и их replication.factor=1
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"

      # конвертеры
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

      # плагины
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components

      # REST
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_REST_PORT: 8083
    volumes:
      - ./connectors:/connectors:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/connectors" ]
      interval: 10s
      timeout: 5s

  init-connect:
    image: alpine:3.17
    depends_on:
      kafka-connect:
        condition: service_healthy
    volumes:
      - ./connectors:/connectors:ro              # JSON-файлы
      - ./scripts/register-connectors.sh:/register.sh:ro  # скрипт
    entrypoint:
      - sh
      - -c
      - |
        # сначала ставим curl и util-linux (для column), затем запускаем скрипт
        apk add --no-cache curl util-linux \
          && sh /register.sh         
    restart: "no"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092


  redis:
    build: ./init/redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./logs/redis:/var/log/redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd
      MONGO_INITDB_DATABASE: university
    volumes:
      - mongodb_data:/data/db
      - ./logs/mongodb:/var/log/mongodb
      - ./config/mongod.conf:/etc/mongod.conf
      - ./init/mongodb:/docker-entrypoint-initdb.d
      - ./config/mongod.conf:/etc/mongod.conf
    command: 
      - mongod
      - --auth
      - --bind_ip_all
      - --config=/etc/mongod.conf
    healthcheck:
      test: |
        mongosh --quiet --eval '
          db.getSiblingDB("admin").auth("admin", "P@ssw0rd");
          db.adminCommand("ping")
        '
      interval: 15s
      timeout: 10s
      retries: 3


  cdc-hierarchy:
    build:
      context: ./mongo_cdc
      dockerfile: Dockerfile
    image: cdc-hierarchy:latest
    container_name: cdc-hierarchy
    depends_on:
      kafka:
        condition: service_started
      mongodb:
        condition: service_healthy
      kafka-connect:
        condition: service_healthy
    environment:
      - KAFKA_BOOTSTRAP=kafka:29092
      - MONGO_URI=mongodb://admin:P%40ssw0rd@mongodb:27017/university?authSource=admin

  mongo-init:
    image: mongo:7.0
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./init/mongodb:/scripts
    command: >
      bash -c "
            until mongosh --host mongodb -u admin -p P@ssw0rd --authenticationDatabase admin --eval 'db.adminCommand(\"ping\")'; do
              sleep 1
            done
            mongosh --host mongodb -u admin -p P@ssw0rd --authenticationDatabase admin --file /scripts/init-mongodb.js
            "
    restart: on-failure

  neo4j_cdc:
    build:
      context: ./neo4j_cdc
      dockerfile: Dockerfile
    image: neo4j-cdc:latest
    container_name: neo4j_cdc
    depends_on:
      kafka:
        condition: service_started
      neo4j:
        condition: service_healthy
      kafka-connect:
        condition: service_healthy
    environment:
      - KAFKA_BOOTSTRAP=kafka:29092
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=P@ssw0rd

  neo4j:
    image: neo4j:5.16-community
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/P@ssw0rd
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_logs_debug_level: INFO
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./logs/neo4j:/logs
      - ./init/neo4j:/var/lib/neo4j/import
    healthcheck:
      test: [ "CMD", "cypher-shell", "-u", "neo4j", "-p", "P@ssw0rd", "RETURN 1" ]
      interval: 20s
      timeout: 15s
      retries: 3

  elasticsearch:
    image: elasticsearch:7.17.10
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./logs/elasticsearch:/usr/share/elasticsearch/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 20s
      retries: 5

  init-es:
    image: alpine:3.17
    container_name: init-es
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./init/elasticsearch:/init
    entrypoint: /bin/sh
    command: [ "-c", "apk add --no-cache curl && chmod +x /init/init-es.sh && sleep 3 && sh /init/init-es.sh" ]

  postgres:
    image: quay.io/debezium/postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: university
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgresql
      - ./init/postgres:/docker-entrypoint-initdb.d
    command: >
      sh -c "
      mkdir -p /var/log/postgresql &&
      chown postgres:postgres /var/log/postgresql &&
      exec docker-entrypoint.sh postgres 
      -c log_destination=stderr 
      -c logging_collector=on 
      -c log_directory='/var/log/postgresql' 
      -c log_filename='postgresql-%Y-%m-%d.log' 
      -c log_rotation_age=1d 
      -c log_rotation_size=0
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=10
      "
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d university" ]
      interval: 15s
      timeout: 10s
      retries: 3

  api_gateway:
    build:
      context: ./app_gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      APP1_URL: ${APP1_URL}
      APP2_URL: ${APP2_URL}
      APP3_URL: ${APP3_URL}
      TOKEN_EXPIRE_MINUTES: ${TOKEN_EXPIRE_MINUTES}
      API_USERS: '${API_USERS}'

  app_1:
    build:
      context: ./app_1
      dockerfile: Dockerfile
    container_name: app1_service
    restart: unless-stopped
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      MONGO_DSN: ${MONGO_DSN}
      JWT_SECRET: ${JWT_SECRET}
      APP2_URL: ${APP2_URL}
      TOKEN_EXPIRE_MINUTES: ${TOKEN_EXPIRE_MINUTES}
      APP1_TOKEN: ${APP1_TOKEN}
      API_USERS: '${API_USERS}'
      POSTGRES_DSN: ${POSTGRES_DSN}
      ES_HOST: ${ES_HOST}
      REDIS_DSN: ${REDIS_DSN}
      NEO4J_URI: "neo4j://neo4j:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "P@ssw0rd"

  app_2:
    build:
      context: ./app_2
      dockerfile: Dockerfile
    container_name: app2_service
    restart: unless-stopped
    ports:
      - "8002:8002"
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      JWT_SECRET: ${JWT_SECRET}
      APP2_URL: ${APP2_URL}
      TOKEN_EXPIRE_MINUTES: ${TOKEN_EXPIRE_MINUTES}
      APP1_TOKEN: ${APP1_TOKEN}
      API_USERS: '${API_USERS}'
      POSTGRES_DSN: ${POSTGRES_DSN}
      ES_HOST: ${ES_HOST}
      REDIS_DSN: ${REDIS_DSN}
      NEO4J_URI: "neo4j://neo4j:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "P@ssw0rd"

  app_3:
    build:
      context: ./app_3
      dockerfile: Dockerfile
    container_name: app3_service
    restart: unless-stopped
    ports:
      - "8003:8003"
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      JWT_SECRET: ${JWT_SECRET}
      APP2_URL: ${APP2_URL}
      TOKEN_EXPIRE_MINUTES: ${TOKEN_EXPIRE_MINUTES}
      APP1_TOKEN: ${APP1_TOKEN}
      API_USERS: '${API_USERS}'
      POSTGRES_DSN: ${POSTGRES_DSN}
      ES_HOST: ${ES_HOST}
      REDIS_DSN: ${REDIS_DSN}
      NEO4J_URI: "neo4j://neo4j:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "P@ssw0rd"

volumes:
  redis_data:
  mongodb_data:
  neo4j_data:
  neo4j_logs:
  elasticsearch_data:
  postgres_data: